language: python
python:
#  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.6 development branch
# command to install dependencies
install:
  - python setup.py install
  - pip install python-e3dc
#  - pip install -r requirements.txt
# command to run tests
script:
  - pytest